// Project serialization and compatibility logic extracted from the original SpinPlot UI.
// Preserve type/version (project: 11; config: 10) and the existing legacy import branches.
import * as TwoD from "../twod/ui.js";

export function createProject({appVersion,sourceType,sourceName,rawCurves,config,created=new Date().toISOString()}){return{type:'SpinPlotProject',version:11,appVersion,created,sourceType,sourceName,rawCurves,config}}

export function validateProjectCurves(curves){if(!Array.isArray(curves)||!curves.length)throw new Error('Project has no curves');for(const [i,c] of curves.entries()){if(c.matrix)TwoD.restore(c.matrix);if(!Array.isArray(c.B)||!Array.isArray(c.y)||c.B.length!==c.y.length||c.B.length<2)throw new Error(`Curve ${i}: B/y lengths differ or are too short`);let direction=0;for(let j=0;j<c.B.length;j++){if(!Number.isFinite(c.B[j]))throw new Error(`Curve ${i}: invalid field at point ${j}`);if(c.y[j]!==null&&!Number.isFinite(c.y[j]))throw new Error(`Curve ${i}: invalid intensity at point ${j}`);if(j){const d=Math.sign(c.B[j]-c.B[j-1]);if(!d||direction&&d!==direction)throw new Error(`Curve ${i}: field must be strictly monotonic`);direction=d}}if(c.freq!=null&&(!Number.isFinite(c.freq)||c.freq<=0))throw new Error(`Curve ${i}: invalid frequency in GHz`)}}

export function validateProjectConfig(cfg,n){if(!cfg)return;if(typeof cfg!=='object'||Array.isArray(cfg))throw new Error('Invalid project config');if(cfg.version!=null&&(!Number.isInteger(cfg.version)||cfg.version<1||cfg.version>10))throw new Error(`Unsupported config version ${cfg.version}`);for(const sp of cfg.subplots||[]){if(sp.twoD&&(!Number.isInteger(sp.twoD.index)||sp.twoD.index<0||sp.twoD.index>=n||!sp.twoD.settings))throw Error('Invalid 2D subplot reference');if(!Array.isArray(sp.curves)||sp.curves.some(i=>!Number.isInteger(i)||i<0||i>=n))throw new Error('Config references an invalid curve index')}}

export function readProjectCurves(o){let curves;if(o.type==='SpinPlotProject'&&Array.isArray(o.rawCurves)){if(!Number.isInteger(o.version)||o.version<9||o.version>11)throw new Error(`Unsupported SpinPlot project version ${o.version}`);curves=o.rawCurves}else if(o.type==='EPRPlotProject'&&o.rawEpr?.length)curves=o.rawEpr.map(c=>({name:c.name||c.source,B:c.B,y:c.y,freq:c.freq,source:c.source||c.name}));else if(o.aligned?.curves&&o.aligned.B)curves=o.aligned.curves.map(c=>({name:c.name,B:o.aligned.B.slice(),y:c.y.slice(),freq:c.freq,source:c.source}));else throw new Error('Invalid project file');return curves}

export function parseProjectCurves(o){const curves=readProjectCurves(o);validateProjectCurves(curves);validateProjectConfig(o.config,curves.length);for(const c of curves)c.y=c.y.map(v=>v===null?NaN:v);for(const sp of o.config?.subplots||[])if(sp.twoD&&!curves[sp.twoD.index]?.matrix)throw Error('2D subplot references non-matrix data');return curves}
