import assert from 'node:assert/strict';
import {axisKind,fieldToGauss} from './core.js';
import {defaults,render,projectionColor,projectionCsv,stackRows,model,plotInsets,sharedMainInsets,fitMainColumns} from './ui.js';
for(const [name,unit,kind]of [['Power','mW','power'],['Angle','deg','angle'],['Temperature','K','temperature'],['Modulation amplitude','mT','modulation'],['Delay','ns','time'],['Field','mT','field']])assert.equal(axisKind({name,unit}),kind);
assert.equal(fieldToGauss({name:'Modulation amplitude',unit:'G'}),null);
assert.equal(fieldToGauss({name:'Field',unit:'mT'}),10);
const d={name:'PRIVATE_FILE.DSC',x:{name:'Power',unit:'mW',values:[1,2]},y:{name:'Field',unit:'mT',values:[300,310]},real:[[1,2],[3,4]],imag:[[0,0],[0,0]]};
const s=defaults(d);assert.equal(s.swap,true);assert.equal(projectionColor(s,{scheme:'matlab'}),'#0072BD');s.projectionScheme='jacs';assert.equal(projectionColor(s,{scheme:'matlab'}),'#1F5A85');s.scheme='plasma';assert.equal(projectionColor(s,{scheme:'matlab'}),'#1F5A85');
function draw(s,title=''){const texts=[];const ctx=new Proxy({drawImage:undefined,fillText:(...a)=>texts.push(a)},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});const g=render(ctx,d,s,{cellX:0,cellY:0,cellW:1000,cellH:700},'Arial',{text:'#000',axis:'#000'},title,{scheme:'matlab',g:{show:true,decimals:3,label:'g factor',titleDistance:22},frequency:9.85,gTicks:(lo,hi)=>[(lo+hi)/2]});return {texts,g};}
const {texts,g}=draw(s,'My spectrum');assert(!texts.some(a=>a[0]===d.name));assert.equal(texts.find(a=>a[0]==='My spectrum')[1],g.titleCenter);assert(texts.some(a=>a[0]==='g factor'));assert(!draw(s).texts.some(a=>a[0]===d.name));s.swap=false;s.xMin=1;s.xMax=2;s.yMin=300;s.yMax=310;s.projectionXMin=1;s.projectionXMax=2;s.projectionYMin=300;s.projectionYMax=310;assert(draw(s).texts.some(a=>a[0]==='g factor'));assert(projectionCsv(d,s).includes('projectionXRange'));
console.log('Shared palette, title center, both magnetic-axis orientations, units and projection CSV passed');

const ms=defaults(d);assert.equal(ms.projectionGapX,20);assert.equal(ms.projectionGapY,20);ms.mode='stack';ms.step=1;assert.equal(stackRows(model(d,ms),ms).length,2);ms.step=2;assert.equal(stackRows(model(d,ms),ms).length,1);
const prs=draw(defaults(d)).g.projectionRegions;assert.equal(prs.length,2);assert.equal(prs[0].projection,'top');assert.equal(prs[1].projection,'side');assert.equal(prs[0].xmin,300);assert.equal(prs[1].ymax,2);
const limits=defaults(d);limits.xProjectionMin=-10;limits.xProjectionMax=10;assert.equal(draw(limits).g.projectionRegions[0].ymin,-10);assert.equal(draw(limits).g.projectionRegions[0].ymax,10);
console.log('Projection geometry, intensity overrides, default gaps and stack decimation passed');

// Equal spans share the drawable main frame, including mixed g visibility.
const box={cellW:600,cellH:500},opts={axisSize:14,g:{show:false,titleDistance:22},frequency:9.85};const map=defaults(d),noG=plotInsets(d,map,box,'',opts),withG=plotInsets(d,map,box,'',{...opts,g:{show:true,titleDistance:22}});const entries=[{index:0,box,insets:{left:56,right:16,top:34,bottom:34},twoD:false},{index:1,box,insets:noG,twoD:true},{index:2,box,insets:withG,twoD:true}];const common=sharedMainInsets(entries);assert.deepEqual(common.get(0),common.get(1));assert.deepEqual(common.get(1),common.get(2));for(const entry of entries)for(const k of ['left','right','top','bottom'])assert(common.get(entry.index)[k]>=entry.insets[k]);const plain=sharedMainInsets([{index:0,box,insets:{left:56,right:16,top:10,bottom:34}},{index:1,box,insets:{left:56,right:16,top:45,bottom:34}}]);assert.equal(plain.get(0).top,45);assert.equal(plain.get(1).top,45);assert.equal(sharedMainInsets([{index:0,box,insets:noG},{index:1,box:{cellW:1200,cellH:500},insets:withG}]).size,0);console.log('Equal-span main frames: mixed 1D/2D, g on/off; explicit unequal spans preserved');

for(const [top,side] of [[true,true],[true,false],[false,true],[false,false]]){const cfg=defaults(d);cfg.showXProjection=top;cfg.showYProjection=side;const r=draw(cfg);assert.deepEqual(r.g.projectionRegions.map(x=>x.projection),[...(top?['top']:[]),...(side?['side']:[])]);assert.equal(r.texts.some(x=>String(x[0]).includes('projection (mean)')),top);assert.equal(r.texts.some(x=>String(x[0]).includes('projection (rms)')),side);}
const labels=defaults(d);const allLabels=draw(labels).texts.map(x=>x[0]);labels.showXProjectionRange=false;labels.showYProjectionRange=false;labels.showXProjectionTitle=false;labels.showYProjectionTitle=false;const hiddenLabels=draw(labels);assert.equal(hiddenLabels.g.projectionRegions.length,2);assert(hiddenLabels.texts.length<allLabels.length);assert(!hiddenLabels.texts.some(x=>String(x[0]).includes('projection (')));
const packed=fitMainColumns(entries.map((e,i)=>({...e,col:i+1})),3,1700);assert(Math.abs(packed.widths.reduce((a,b)=>a+b,0)-1700)<1e-8);for(let i=0;i<3;i++)assert(Math.abs(packed.widths[i]-packed.insets[i].left-packed.insets[i].right-packed.width)<1e-8);assert(packed.widths[0]<packed.widths[1]);const hidden=defaults(d);hidden.showYProjection=false;const hiddenInsets=plotInsets(d,hidden,box,'',opts);assert(hiddenInsets.right<noG.right);assert.equal(hiddenInsets.rightFraction,0);console.log('Independent projection visibility and compact equal-width main columns passed');
