import {orient,projections,validate} from './core.js';
import {COLOR_SCHEMES} from './palettes.js';
export function defaults(d){const swap=/time/i.test(d.x.name)||/^(ns|us|µs|ms|s)$/i.test(d.x.unit),v=orient(d,'real',swap),xMin=Math.min(v.x.values[0],v.x.values.at(-1)),xMax=Math.max(v.x.values[0],v.x.values.at(-1)),yMin=Math.min(v.y.values[0],v.y.values.at(-1)),yMax=Math.max(v.y.values[0],v.y.values.at(-1));return{swap,component:'real',mode:'heatmap',xMode:'mean',yMode:'rms',xMin,xMax,yMin,yMax,projectionXMin:xMin,projectionXMax:xMax,projectionYMin:yMin,projectionYMax:yMax,showProjectionRanges:true,xRangeLabelX:50,xRangeLabelY:93,yRangeLabelX:50,yRangeLabelY:-3,zMin:'',zMax:'',scheme:'inherit',showColorbar:true,colorbarLabel:'Intensity',xLabel:'',yLabel:'',xProjectionTitle:'',yProjectionTitle:'',step:Math.max(1,Math.ceil(v.y.values.length/24)),offset:1,showProjections:true,open:true};}
export function migrate(d,s){const base=defaults(d);for(const [k,v]of Object.entries(base))if(s[k]===undefined)s[k]=v;return s;}
export function restore(d){for(const key of ['real','imag']){if(!Array.isArray(d[key])||d[key].length!==d.y.values.length||d[key].some(r=>!Array.isArray(r)||r.length!==d.x.values.length))throw Error('Invalid 2D signal dimensions');for(const row of d[key])for(let i=0;i<row.length;i++){if(row[i]===null)row[i]=NaN;else if(!Number.isFinite(row[i]))throw Error('Invalid 2D signal');}}return validate(d);}
const cache=new WeakMap();
export function model(d,s){migrate(d,s);const key=JSON.stringify(s),cached=cache.get(d);if(cached?.key===key)return cached.value;const v=orient(d,s.component,s.swap),xr=[Number(s.xMin),Number(s.xMax)],yr=[Number(s.yMin),Number(s.yMax)],pxr=[Number(s.projectionXMin),Number(s.projectionXMax)],pyr=[Number(s.projectionYMin),Number(s.projectionYMax)];for(const r of [xr,yr,pxr,pyr])if(r.some(x=>!Number.isFinite(x))||r[0]>=r[1])throw Error('Invalid 2D or projection ranges');if(!Number.isInteger(Number(s.step))||s.step<1||!Number.isFinite(Number(s.offset))||s.offset<0)throw Error('Invalid 2D stack settings');const p=projections(v,pxr,pyr,s.xMode,s.yMode),xi=v.x.values.map((z,i)=>z>=xr[0]&&z<=xr[1]?i:-1).filter(i=>i>=0),yi=v.y.values.map((z,i)=>z>=yr[0]&&z<=yr[1]?i:-1).filter(i=>i>=0);if(!xi.length||!yi.length)throw Error('Display range contains no samples');let lo=Infinity,hi=-Infinity;for(const j of yi)for(const i of xi){const z=v.z[j][i];if(Number.isFinite(z)){lo=Math.min(lo,z);hi=Math.max(hi,z);}}if(!Number.isFinite(lo)){lo=0;hi=1;}if(lo===hi){lo-=.5;hi+=.5;}const zmin=s.zMin===''?lo:Number(s.zMin),zmax=s.zMax===''?hi:Number(s.zMax);if(!Number.isFinite(zmin)||!Number.isFinite(zmax)||zmin>=zmax)throw Error('Z min must be less than Z max');const value={v,p,xr,yr,pxr,pyr,xi,yi,zmin,zmax,max:Math.max(Math.abs(lo),Math.abs(hi))||1};cache.set(d,{key,value});return value;}
export function controls(card,sp,d,onChange){const s=migrate(d,sp.twoD.settings);const box=document.createElement('details');box.open=s.open!==false;box.className='twod-options';box.style.cssText='margin:8px 0;padding:6px;border:1px solid #999';const summary=document.createElement('summary');summary.textContent='2D · '+d.x.name+' ('+d.x.unit+') × '+d.y.name+' ('+d.y.unit+') · '+d.x.values.length+' × '+d.y.values.length;box.append(summary);const body=document.createElement('div');body.className='grid2';box.append(body);
 const select=(key,title,options)=>{const l=document.createElement('label');l.textContent=title;const e=document.createElement('select');for(const [value,text]of options){const o=document.createElement('option');o.value=value;o.textContent=text;e.append(o);}e.value=s[key];e.onchange=()=>{s[key]=e.value;onChange();};l.append(e);body.append(l);};
 select('mode','View',[['heatmap','Heatmap'],['stack','Stack']]);select('component','Signal',[['real','Real'],['imag','Imaginary'],['magnitude','Magnitude']]);for(const key of ['xMode','yMode'])select(key,key==='xMode'?'X projection':'Y projection',[['mean','Mean'],['max','Maximum'],['min','Minimum'],['ptp','Peak-to-peak (max − min)'],['rms','RMS'],['sum','Sum']]);
 for(const [key,title]of [['zMin','Z min (blank = auto)'],['zMax','Z max (blank = auto)'],['projectionXMin','Y projection: X min'],['projectionXMax','Y projection: X max'],['projectionYMin','X projection: Y min'],['projectionYMax','X projection: Y max'],['xRangeLabelX','X projection range label: horizontal (%)'],['xRangeLabelY','X projection range label: vertical (%)'],['yRangeLabelX','Y projection range label: horizontal (%)'],['yRangeLabelY','Y projection range label: vertical (%)'],['xMin','X min'],['xMax','X max'],['yMin','Y min'],['yMax','Y max'],['step','Stack every'],['offset','Stack offset']]){const l=document.createElement('label');l.textContent=title;const e=document.createElement('input');e.type='number';e.step=key==='step'?'1':'any';e.value=s[key];e.dataset.twod=key;e.onchange=()=>{s[key]=e.value===''&&(key==='zMin'||key==='zMax')?'':e.value===''?NaN:Number(e.value);onChange();};l.append(e);body.append(l);}
 for(const [key,title]of [['swap','Swap axes'],['showProjections','Show projections'],['showProjectionRanges','Show projection ranges'],['showColorbar','Show colorbar']]){const l=document.createElement('label'),e=document.createElement('input');e.type='checkbox';e.checked=s[key];e.onchange=()=>{s[key]=e.checked;if(key==='swap'){const b=defaults(d);const v=orient(d,s.component,s.swap);for(const [k,a]of [['x',v.x],['y',v.y]]){s[k+'Min']=Math.min(a.values[0],a.values.at(-1));s[k+'Max']=Math.max(a.values[0],a.values.at(-1));s['projection'+k.toUpperCase()+'Min']=s[k+'Min'];s['projection'+k.toUpperCase()+'Max']=s[k+'Max'];}for(const input of body.querySelectorAll('input[data-twod]'))input.value=s[input.dataset.twod];}onChange();};l.append(e,document.createTextNode(title));body.append(l);}
 select('scheme','Heatmap palette',[['inherit','Inherit subplot / global'],...Object.entries(COLOR_SCHEMES).filter(([k,v])=>v.gradient).map(([k,v])=>[k,v.label])]);for(const [key,title]of [['xLabel','X axis title (blank = file)'],['yLabel','Y axis title (blank = file)'],['xProjectionTitle','X projection title (blank = auto)'],['yProjectionTitle','Y projection title (blank = auto)'],['colorbarLabel','Colorbar title']]){const l=document.createElement('label');l.textContent=title;const e=document.createElement('input');e.value=s[key];e.onchange=()=>{s[key]=e.value;onChange();};l.append(e);body.append(l);}const autoZ=document.createElement('button');autoZ.textContent='Auto Z';autoZ.onclick=()=>{s.zMin='';s.zMax='';body.querySelector('[data-twod=zMin]').value='';body.querySelector('[data-twod=zMax]').value='';onChange();};body.append(autoZ);const exportButton=document.createElement('button');exportButton.textContent='Projection CSV';exportButton.onclick=()=>{try{const {v,p,xr,yr,pxr,pyr}=model(d,s);const lines=['# '+JSON.stringify({x:v.x.name,xUnit:v.x.unit,y:v.y.name,yUnit:v.y.unit,displayXRange:xr,displayYRange:yr,projectionXRange:pxr,projectionYRange:pyr,xMode:s.xMode,yMode:s.yMode,component:s.component}),'axis,coordinate,projection'];for(let i=0;i<v.x.values.length;i++)lines.push('X,'+v.x.values[i]+','+p.x[i]);for(let j=0;j<v.y.values.length;j++)lines.push('Y,'+v.y.values[j]+','+p.y[j]);const u=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='SpinPlot_2D_projection.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){alert(e.message);}};body.append(exportButton);box.ontoggle=()=>{s.open=box.open;};card.querySelector('.subplot-body').prepend(box);
 // 2D uses its own axis/projection controls; curve ordering and 1D processing are inapplicable.
 for(const e of card.querySelectorAll('.curve-manager'))e.style.display='none';for(const e of card.querySelectorAll('[data-action=startNoise],[data-action=confirmNoise],[data-field=noiseRegions]')){e.disabled=true;e.title='Noise region selection is for 1D spectra';}for(const field of ['freqMode','localFreqMode','localFreqTarget','localFreqConfirmed','gShow','gTickMode','gUseGlobal'])for(const e of card.querySelectorAll('[data-field='+field+']')){e.disabled=true;e.title='1D setting; 2D preserves acquisition axes';}for(const field of ['mode','offsetMode','offsetScale','manualOffsets','offsetDirection'])for(const e of card.querySelectorAll('[data-field='+field+']')){e.disabled=true;e.title='Use View and Stack settings in the 2D section';}}
function extent(a,ids){let lo=Infinity,hi=-Infinity;for(const i of ids){const v=a[i];if(Number.isFinite(v)){lo=Math.min(lo,v);hi=Math.max(hi,v);}}if(!Number.isFinite(lo))return[0,1];return[lo,hi===lo?lo+1:hi];}
function edge(a,i){return[i?(a[i-1]+a[i])/2:a[i]-(a[1]-a[0])/2,i<a.length-1?(a[i]+a[i+1])/2:a[i]+(a[i]-a[i-1])/2];}
function cellIndex(a,v){const asc=a.at(-1)>a[0],n=a.length;let lo=0,hi=n-1;while(lo<hi){const mid=(lo+hi)>>1,b=(a[mid]+a[mid+1])/2;if(asc?v>b:v<b)lo=mid+1;else hi=mid;}return lo;}
export function color(stops,t){t=Math.max(0,Math.min(1,t));const p=t*(stops.length-1),i=Math.min(stops.length-2,Math.floor(p)),u=p-i,a=stops[i],b=stops[i+1];return [1,3,5].map(k=>Math.round(parseInt(a.slice(k,k+2),16)*(1-u)+parseInt(b.slice(k,k+2),16)*u));}
const css=c=>`rgb(${c.join(',')})`;
export function colorStops(s,options={}){const key=s.scheme!=='inherit'?s.scheme:options.scheme;return (COLOR_SCHEMES[key]?.gradient)||COLOR_SCHEMES.turbo.gradient;}
export function raster(m,width,height,stops=COLOR_SCHEMES.turbo.gradient){const {v,xr,yr,zmin,zmax}=m,canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const c=canvas.getContext('2d'),image=c.createImageData(width,height),xs=Array.from({length:width},(_,i)=>cellIndex(v.x.values,xr[0]+(i+.5)/width*(xr[1]-xr[0]))),ys=Array.from({length:height},(_,j)=>cellIndex(v.y.values,yr[1]-(j+.5)/height*(yr[1]-yr[0])));for(let j=0;j<height;j++)for(let i=0;i<width;i++){const z=v.z[ys[j]][xs[i]],k=(j*width+i)*4;if(!Number.isFinite(z))continue;const c=color(stops,(z-zmin)/(zmax-zmin));image.data.set(c,k);image.data[k+3]=255;}c.putImageData(image,0,0);return canvas;}
export function adjustZ(s,m,delta){const factor=delta>0?1.15:1/1.15,center=(m.zmin+m.zmax)/2,half=(m.zmax-m.zmin)*factor/2;if(!Number.isFinite(half)||half<=Number.EPSILON*Math.max(1,Math.abs(center)))return;s.zMin=center-half;s.zMax=center+half;}
export function render(ctx,d,s,box,font,theme,title,options={}){
 const m=model(d,s),{v,p,xr,yr,pxr,pyr,xi,yi,zmin,zmax,max}=m,{cellX:cx,cellY:cy,cellW:w,cellH:h}=box,proj=s.showProjections,cb=s.showColorbar&&s.mode==='heatmap',stops=colorStops(s,options),tick=options.tickSize||11,axisSize=options.axisSize||14,titleSize=options.titleSize||15,lineWidth=options.lineWidth||1.4;
 const left=Math.max(52,options.yTitleDistance||35),x=cx+left,y=cy+(proj?h*.28:42),right=proj?w*.29:cb?75:20,pw=w-left-right,ph=h-(y-cy)-Math.max(55,(options.xTitleDistance||20)+axisSize+20),X=a=>x+(a-xr[0])/(xr[1]-xr[0])*pw,Y=a=>y+ph-(a-yr[0])/(yr[1]-yr[0])*ph;
 if(pw<35||ph<35)throw Error('2D subplot too small for map and projections');
 const top={x,y:cy+30,w:pw,h:proj?Math.max(25,h*.17):0},side={x:x+pw+w*.035,y,w:w*.14,h:ph},bar={x:proj?side.x+side.w+w*.035:x+pw+18,y,w:Math.max(8,w*.018),h:ph};
 ctx.save();ctx.font=tick+'px '+font;ctx.fillStyle=theme.text;ctx.strokeStyle=theme.axis;ctx.lineWidth=lineWidth;ctx.textAlign='center';ctx.textBaseline='middle';
 function text(t,x,y,size=tick,align='center'){ctx.font=size+'px '+font;ctx.fillStyle=theme.text;ctx.textAlign=align;ctx.fillText(t,x,y);}
 function line(ids,get,col=options.projectionColor||'#0072BD'){ctx.strokeStyle=col;ctx.lineWidth=lineWidth;ctx.beginPath();let open=false;for(const i of ids){const [px,py]=get(i);if(!Number.isFinite(px)||!Number.isFinite(py)){open=false;continue;}if(open)ctx.lineTo(px,py);else ctx.moveTo(px,py);open=true;}ctx.stroke();}
 function clip(r,fn){ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.w,r.h);ctx.clip();fn();ctx.restore();}
 function border(r){ctx.strokeStyle=theme.axis;ctx.lineWidth=theme.axisWidth||1;ctx.strokeRect(r.x,r.y,r.w,r.h);}
 const mapBox={x,y,w:pw,h:ph};clip(mapBox,()=>{
 if(s.mode==='heatmap'){
 if(typeof ctx.drawImage==='function'){const scale=Math.min(2,window.devicePixelRatio||1),image=raster(m,Math.max(1,Math.ceil(pw*scale)),Math.max(1,Math.ceil(ph*scale)),stops);ctx.drawImage(image,x,y,pw,ph);}else for(const j of yi){const ye=edge(v.y.values,j).map(Y);for(const i of xi){const z=v.z[j][i];if(!Number.isFinite(z))continue;const xe=edge(v.x.values,i).map(X);ctx.fillStyle=css(color(stops,(z-zmin)/(zmax-zmin)));ctx.fillRect(Math.min(...xe),Math.min(...ye),Math.abs(xe[1]-xe[0]),Math.abs(ye[1]-ye[0]));}}
 }else{const rows=yi.filter((_,k)=>k%Number(s.step)===0);rows.forEach((j,k)=>{const base=y+ph*.94-k*ph*.86/Math.max(1,rows.length-1);line(xi,i=>[X(v.x.values[i]),base-v.z[j][i]/max*Number(s.offset)*ph*.4/Math.max(1,rows.length)],css(color(stops,k/Math.max(1,rows.length-1))));if(options.labels!=='none')text(v.y.values[j].toPrecision(4)+' '+v.y.unit,x+pw-4,base,tick,'right');});}
 if(options.grid){ctx.strokeStyle=theme.majorGrid;ctx.lineWidth=.5;for(let k=1;k<4;k++){ctx.beginPath();ctx.moveTo(x+pw*k/4,y);ctx.lineTo(x+pw*k/4,y+ph);ctx.moveTo(x,y+ph*k/4);ctx.lineTo(x+pw,y+ph*k/4);ctx.stroke();}}
 });
 if(options.frame!=='none')border(mapBox);text(title||d.name,x+pw/2,y-17,titleSize);
 for(let k=0;k<=4;k++){const a=xr[0]+(xr[1]-xr[0])*k/4,b=yr[0]+(yr[1]-yr[0])*k/4;text(a.toPrecision(4),X(a),y+ph+tick+3);if(options.showYTicks!==false)text(b.toPrecision(4),x-6,Y(b),tick,'right');}
 text(s.xLabel||v.x.name+' ('+v.x.unit+')',x+pw/2,y+ph+(options.xTitleDistance||20)+tick+8,axisSize);
 if(options.showYTitle!==false){ctx.save();ctx.translate(x-(options.yTitleDistance||46),y+ph/2);ctx.rotate(-Math.PI/2);text(s.yLabel||v.y.name+' ('+v.y.unit+')',0,0,axisSize);ctx.restore();}
 if(proj){
 const [a0,b0]=extent(p.x,xi),[c0,e0]=extent(p.y,yi),ap=(b0-a0)*.08,cp=(e0-c0)*.08,a=a0-ap,b=b0+ap,c=c0-cp,e=e0+cp;
 const XP=z=>top.y+top.h-(z-a)/(b-a)*top.h,YP=z=>side.x+(z-c)/(e-c)*side.w;
 clip(top,()=>line(xi,i=>[X(v.x.values[i]),XP(p.x[i])]));clip(side,()=>line(yi,j=>[YP(p.y[j]),Y(v.y.values[j])]));border(top);border(side);
 for(let k=0;k<=3;k++){const z=a+(b-a)*k/3,q=c+(e-c)*k/3;text(z.toPrecision(3),top.x-5,XP(z),tick,'right');text(q.toPrecision(3),YP(q),side.y+side.h+tick+3);}
 // Both projection frames share coordinate ticks with the map (labels omitted).
 ctx.strokeStyle=theme.axis;for(let k=0;k<=4;k++){ctx.beginPath();ctx.moveTo(x+pw*k/4,top.y);ctx.lineTo(x+pw*k/4,top.y+5);ctx.moveTo(x+pw*k/4,top.y+top.h);ctx.lineTo(x+pw*k/4,top.y+top.h-5);ctx.moveTo(side.x,y+ph*k/4);ctx.lineTo(side.x+5,y+ph*k/4);ctx.moveTo(side.x+side.w,y+ph*k/4);ctx.lineTo(side.x+side.w-5,y+ph*k/4);ctx.stroke();}
 const rangeText=(r,axis)=>`${r[0].toPrecision(4)}–${r[1].toPrecision(4)} ${axis.unit}`;
 text(s.xProjectionTitle||`${v.x.name} projection (${s.xMode})`,top.x+top.w/2,cy+10,tick);
 text(s.yProjectionTitle||`${v.y.name} projection (${s.yMode})`,side.x+side.w/2,y-28,tick);
 if(s.showProjectionRanges){text(rangeText(pyr,v.y),top.x+top.w*Number(s.xRangeLabelX)/100,top.y+top.h*Number(s.xRangeLabelY)/100,Math.max(8,tick-1));text(rangeText(pxr,v.x),side.x+side.w*Number(s.yRangeLabelX)/100,side.y+side.h*Number(s.yRangeLabelY)/100,Math.max(8,tick-1));}
 }
 if(cb){for(let k=0;k<256;k++){ctx.fillStyle=css(color(stops,1-k/255));ctx.fillRect(bar.x,bar.y+bar.h*k/256,bar.w,bar.h/256+.1);}border(bar);for(let k=0;k<=4;k++){const z=zmin+(zmax-zmin)*k/4,py=y+ph-ph*k/4;ctx.strokeStyle=theme.axis;ctx.beginPath();ctx.moveTo(bar.x+bar.w,py);ctx.lineTo(bar.x+bar.w+4,py);ctx.stroke();text(z.toPrecision(4),bar.x+bar.w+6,py,tick,'left');}if(s.colorbarLabel){ctx.save();ctx.translate(bar.x+bar.w+56,y+ph/2);ctx.rotate(-Math.PI/2);text(s.colorbarLabel,0,0,tick);ctx.restore();}}
 ctx.restore();return{x0:x,y0:y,pw,ph,xmin:xr[0],xmax:xr[1],ymin:yr[0],ymax:yr[1],...box,twoD:true,colorbar:cb?bar:null,zmin,zmax};
}
