import {parseCIQ,parseBES,orient,projections} from './core.js';
const button=document.createElement('button');button.textContent='2D Map';button.title='二维数据、热图、堆叠图与投影';document.querySelector('.top-actions').append(button);
const panel=document.createElement('dialog');panel.style.cssText='width:min(1200px,96vw);height:94vh;background:#e7e5de;overflow:auto;border:1px solid #394148';
panel.innerHTML=`<div style="display:flex;gap:8px;align-items:center"><b>2D EPR</b><label class="btn">Open 2D<input id="mfiles" type="file" multiple accept=".epr,.dsc,.DSC,.dta,.DTA,.xgf,.XGF,.ygf,.YGF"></label><button id="mclose">Close</button></div><p id="minfo">Import CIQTEK 2D .epr or matching DSC/DTA (+ XGF/YGF for irregular axes).</p><div id="mcontrols" style="display:flex;flex-wrap:wrap;gap:10px;align-items:center"><label>View <select id="mview"><option>Heatmap</option><option>Stack</option></select></label><label>Signal <select id="msignal"><option value="real">Real</option><option value="imag">Imaginary</option><option value="magnitude">Magnitude</option></select></label><label><input id="mswap" type="checkbox"> Swap axes</label><label>X projection <select id="mxmode"><option value="mean">Mean</option><option value="sum">Sum</option><option value="rms">RMS</option></select></label><label>Y projection <select id="mymode"><option value="rms">RMS</option><option value="mean">Mean</option><option value="sum">Sum</option></select></label><label>Stack every <input id="mstep" type="number" min="1" value="1" style="width:55px"></label><label>Offset <input id="moffset" type="number" min="0" step="0.1" value="1" style="width:55px"></label><label>X range <input id="mxlo" type="number" step="any" style="width:100px"> – <input id="mxhi" type="number" step="any" style="width:100px"></label><label>Y range <input id="mylo" type="number" step="any" style="width:100px"> – <input id="myhi" type="number" step="any" style="width:100px"></label><button id="msvg">SVG</button><button id="mcsv">Projection CSV</button><button id="mproject">Save 2D project</button><label class="btn">Open 2D project<input id="mload" type="file" accept=".json"></label></div><p id="merror" style="color:#9a4747"></p><div id="mfigure" style="background:white;margin-top:8px"></div>`;
document.body.append(panel);const $=id=>panel.querySelector('#'+id);let data=null,view=null,result=null;
button.onclick=()=>panel.showModal();$('mclose').onclick=()=>panel.close();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function range(a){let lo=Infinity,hi=-Infinity;for(const v of a)if(Number.isFinite(v)){lo=Math.min(lo,v);hi=Math.max(hi,v);}return Number.isFinite(lo)?[lo,hi===lo?lo+1:hi]:[0,1];}
function bounds(){view=orient(data,$('msignal').value,$('mswap').checked);for(const [k,a] of [['x',view.x],['y',view.y]]){const r=range(a.values);$('m'+k+'lo').value=r[0];$('m'+k+'hi').value=r[1];}}
function install(d){data=d;$('mswap').checked=/time/i.test(d.x.name)||/^(ns|us|µs|ms|s)$/i.test(d.x.unit);bounds();$('minfo').textContent=d.name+' · '+d.x.name+' ('+d.x.unit+') × '+d.y.name+' ('+d.y.unit+') · '+d.x.values.length+' × '+d.y.values.length;render();}
$('mfiles').onchange=async e=>{try{const fs=[...e.target.files],sources=fs.filter(f=>/\.(epr|dsc)$/i.test(f.name));if(sources.length!==1)throw Error('Select exactly one dataset plus companion files');const f=sources[0];install(/\.epr$/i.test(f.name)?parseCIQ(JSON.parse(await f.text()),f.name):await parseBES(f,fs));}catch(e){$('merror').textContent=e.message;}};
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function render(){if(!data)return;try{view=orient(data,$('msignal').value,$('mswap').checked);const xr=[Number($('mxlo').value),Number($('mxhi').value)],yr=[Number($('mylo').value),Number($('myhi').value)];if([...xr,...yr].some(v=>!Number.isFinite(v))||xr[0]>=xr[1]||yr[0]>=yr[1])throw Error('Invalid axis ranges');result=projections(view,xr,yr,$('mxmode').value,$('mymode').value);
 const step=Number($('mstep').value),offset=Number($('moffset').value);if(!Number.isInteger(step)||step<1||!Number.isFinite(offset)||offset<0)throw Error('Invalid stack controls');
 const X=v=>90+(v-xr[0])/(xr[1]-xr[0])*650,Y=v=>620-(v-yr[0])/(yr[1]-yr[0])*400;let s='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 730" width="100%"><rect width="1100" height="730" fill="white"/><defs><clipPath id="map"><rect x="90" y="220" width="650" height="400"/></clipPath></defs>';const text=(x,y,t)=>`<text x="${x}" y="${y}" font-family="Arial" font-size="14">${esc(t)}</text>`;
 const line=(a,b,c,d)=>`<path d="M${a},${b}L${c},${d}" fill="none" stroke="#555"/>`;
 function path(coords,color='#173f5f'){let d='',open=false;for(const [x,y] of coords){if(!Number.isFinite(y)||!Number.isFinite(x)){open=false;continue;}d+=(open?'L':'M')+x+','+y;open=true;}return `<path d="${d}" fill="none" stroke="${color}" stroke-width="1.2"/>`;}
 const xiSet=new Set(result.xi),yiSet=new Set(result.yi);const zx=range(result.x),zy=range(result.y);s+=path(result.x.map((z,i)=>[X(view.x.values[i]),180-(z-zx[0])/(zx[1]-zx[0])*120]).filter((_,i)=>xiSet.has(i)));s+=path(result.y.map((z,j)=>[800+(z-zy[0])/(zy[1]-zy[0])*180,Y(view.y.values[j])]).filter((_,j)=>yiSet.has(j)));
 if($('mview').value==='Heatmap'&&result.xi.length*result.yi.length>250000)throw Error('Vector heatmap limited to 250,000 cells. Narrow X/Y ranges or use Stack.');let max=0;for(const j of result.yi)for(const i of result.xi)if(Number.isFinite(view.z[j][i]))max=Math.max(max,Math.abs(view.z[j][i]));max=max||1;
 s+='<g clip-path="url(#map)">';if($('mview').value==='Heatmap'){
 function edges(a,i){return [i? (a[i-1]+a[i])/2:a[i]-(a[1]-a[0])/2,i<a.length-1?(a[i]+a[i+1])/2:a[i]+(a[i]-a[i-1])/2];}
 // Exact cell boundaries retain nonuniform spacing. Heatmap cells are SVG rectangles.
 for(const j of result.yi){const ye=edges(view.y.values,j).map(Y);for(const i of result.xi){const v=view.z[j][i];if(!Number.isFinite(v))continue;const xe=edges(view.x.values,i).map(X),t=Math.min(1,Math.abs(v)/max),c=Math.round(255*(1-t)),color=v>=0?`rgb(255,${c},${c})`:`rgb(${c},${c},255)`;s+=`<rect x="${Math.min(...xe)}" y="${Math.min(...ye)}" width="${Math.abs(xe[1]-xe[0])+0.01}" height="${Math.abs(ye[1]-ye[0])+0.01}" fill="${color}"/>`;}}
 }else{const rows=result.yi.filter((_,i)=>i%step===0);rows.forEach((j,k)=>{const base=590-k*340/Math.max(1,rows.length-1),scale=offset*140/Math.max(1,rows.length);s+=path(result.xi.map(i=>[X(view.x.values[i]),base-view.z[j][i]/max*scale]));s+=text(600,base,view.y.values[j].toPrecision(4)+' '+view.y.unit);});}
 s+='</g>';s+=line(90,620,740,620)+line(90,220,90,620)+line(90,180,740,180)+line(800,620,980,620);
 for(let k=0;k<=4;k++){const x=xr[0]+(xr[1]-xr[0])*k/4,y=yr[0]+(yr[1]-yr[0])*k/4;s+=text(X(x)-15,644,x.toPrecision(4))+text(5,Y(y),y.toPrecision(4));}
 s+=text(250,690,view.x.name+' ('+view.x.unit+')')+text(90,210,view.y.name+' ('+view.y.unit+')')+text(90,35,data.name)+text(90,55,'X projection: '+$('mxmode').value+' over Y '+yr.join(' – ')+' '+view.y.unit)+text(800,210,'Y projection: '+$('mymode').value);
 s+=text(90,715,$('mview').value==='Heatmap'?'Blue −'+max.toPrecision(4)+' · white 0 · red +'+max.toPrecision(4):'Stack labels: '+view.y.name+'; vertical offsets are display only');s+='</svg>';$('mfigure').innerHTML=s;$('merror').textContent='';
 }catch(e){$('merror').textContent=e.message;$('mfigure').innerHTML='';result=null;}}
$('mcontrols').addEventListener('change',e=>{if(e.target.id==='mswap')bounds();render();});
$('msvg').onclick=()=>{if(result)download('SpinPlot_2D.svg',$('mfigure').innerHTML,'image/svg+xml');};
$('mcsv').onclick=()=>{if(!result)return;const rows=['# '+JSON.stringify({x:view.x.name,xUnit:view.x.unit,y:view.y.name,yUnit:view.y.unit,signal:$('msignal').value,xMode:$('mxmode').value,yMode:$('mymode').value,xRange:[$('mxlo').value,$('mxhi').value],yRange:[$('mylo').value,$('myhi').value]}),'axis,coordinate,projection'];for(const i of result.xi)rows.push('X,'+view.x.values[i]+','+result.x[i]);for(const j of result.yi)rows.push('Y,'+view.y.values[j]+','+result.y[j]);download('SpinPlot_2D_projections.csv',rows.join('\n'),'text/csv');};
$('mproject').onclick=()=>{if(data)download('SpinPlot_2D.json',JSON.stringify({type:'SpinPlot2D',version:1,data,settings:Object.fromEntries([...$('mcontrols').querySelectorAll('input,select')].filter(e=>e.type!=='file').map(e=>[e.id,e.type==='checkbox'?e.checked:e.value]))}),'application/json');};
$('mload').onchange=async e=>{try{const o=JSON.parse(await e.target.files[0].text());if(o.type!=='SpinPlot2D'||o.version!==1)throw Error('Unsupported 2D project');const {validate}=await import('./core.js');if(!o.data.imag||o.data.imag.length!==o.data.real.length||o.data.imag.some(r=>r.length!==o.data.x.values.length))throw Error('Invalid imaginary matrix');for(const rows of [o.data.real,o.data.imag])for(const row of rows)for(let i=0;i<row.length;i++)if(row[i]===null)row[i]=NaN;install(validate(o.data));for(const [id,v] of Object.entries(o.settings||{})){const e=$(id);if(e&&e.type!=='file'){if(e.type==='checkbox')e.checked=Boolean(v);else e.value=v;}}render();}catch(e){$('merror').textContent=e.message;}};
