import {orient,projections,validate} from './core.js';
export function defaults(d){const swap=/time/i.test(d.x.name)||/^(ns|us|µs|ms|s)$/i.test(d.x.unit),v=orient(d,'real',swap);return{swap,component:'real',mode:'heatmap',xMode:'mean',yMode:'rms',xMin:Math.min(v.x.values[0],v.x.values.at(-1)),xMax:Math.max(v.x.values[0],v.x.values.at(-1)),yMin:Math.min(v.y.values[0],v.y.values.at(-1)),yMax:Math.max(v.y.values[0],v.y.values.at(-1)),step:1,offset:1,showProjections:true,open:true};}
export function restore(d){for(const key of ['real','imag']){if(!Array.isArray(d[key])||d[key].length!==d.y.values.length||d[key].some(r=>!Array.isArray(r)||r.length!==d.x.values.length))throw Error('Invalid 2D signal dimensions');for(const row of d[key])for(let i=0;i<row.length;i++){if(row[i]===null)row[i]=NaN;else if(!Number.isFinite(row[i]))throw Error('Invalid 2D signal');}}return validate(d);}
const cache=new WeakMap();
export function model(d,s){const key=JSON.stringify(s),cached=cache.get(d);if(cached?.key===key)return cached.value;const v=orient(d,s.component,s.swap),xr=[Number(s.xMin),Number(s.xMax)],yr=[Number(s.yMin),Number(s.yMax)];if([...xr,...yr].some(x=>!Number.isFinite(x))||xr[0]>=xr[1]||yr[0]>=yr[1])throw Error('Invalid 2D ranges');if(!Number.isInteger(Number(s.step))||s.step<1||!Number.isFinite(Number(s.offset))||s.offset<0)throw Error('Invalid 2D stack settings');const p=projections(v,xr,yr,s.xMode,s.yMode);let max=0;for(const j of p.yi)for(const i of p.xi)if(Number.isFinite(v.z[j][i]))max=Math.max(max,Math.abs(v.z[j][i]));const value={v,p,xr,yr,max:max||1};cache.set(d,{key,value});return value;}
export function controls(card,sp,d,onChange){const s=sp.twoD.settings;const box=document.createElement('details');box.open=s.open!==false;box.className='twod-options';box.style.cssText='margin:8px 0;padding:6px;border:1px solid #999';const summary=document.createElement('summary');summary.textContent='2D · '+d.x.name+' ('+d.x.unit+') × '+d.y.name+' ('+d.y.unit+') · '+d.x.values.length+' × '+d.y.values.length;box.append(summary);const body=document.createElement('div');body.className='grid2';box.append(body);
 const select=(key,title,options)=>{const l=document.createElement('label');l.textContent=title;const e=document.createElement('select');for(const [value,text]of options){const o=document.createElement('option');o.value=value;o.textContent=text;e.append(o);}e.value=s[key];e.onchange=()=>{s[key]=e.value;onChange();};l.append(e);body.append(l);};
 select('mode','View',[['heatmap','Heatmap'],['stack','Stack']]);select('component','Signal',[['real','Real'],['imag','Imaginary'],['magnitude','Magnitude']]);for(const key of ['xMode','yMode'])select(key,key==='xMode'?'X projection':'Y projection',[['mean','Mean'],['rms','RMS'],['sum','Sum']]);
 for(const [key,title]of [['xMin','X min'],['xMax','X max'],['yMin','Y min'],['yMax','Y max'],['step','Stack every'],['offset','Stack offset']]){const l=document.createElement('label');l.textContent=title;const e=document.createElement('input');e.type='number';e.step=key==='step'?'1':'any';e.value=s[key];e.onchange=()=>{s[key]=e.value===''?NaN:Number(e.value);onChange();};l.append(e);body.append(l);}
 for(const [key,title]of [['swap','Swap axes'],['showProjections','Show projections']]){const l=document.createElement('label'),e=document.createElement('input');e.type='checkbox';e.checked=s[key];e.onchange=()=>{s[key]=e.checked;if(key==='swap'){const b=defaults(d);const v=orient(d,s.component,s.swap);for(const [k,a]of [['x',v.x],['y',v.y]]){s[k+'Min']=Math.min(a.values[0],a.values.at(-1));s[k+'Max']=Math.max(a.values[0],a.values.at(-1));}for(const input of body.querySelectorAll('input[type=number]')){const label=input.parentElement.textContent;const map={'X min':'xMin','X max':'xMax','Y min':'yMin','Y max':'yMax'};if(map[label])input.value=s[map[label]];}}onChange();};l.append(e,document.createTextNode(title));body.append(l);}
 const exportButton=document.createElement('button');exportButton.textContent='Projection CSV';exportButton.onclick=()=>{try{const {v,p,xr,yr}=model(d,s);const lines=['# '+JSON.stringify({x:v.x.name,xUnit:v.x.unit,y:v.y.name,yUnit:v.y.unit,xRange:xr,yRange:yr,xMode:s.xMode,yMode:s.yMode,component:s.component}),'axis,coordinate,projection'];for(const i of p.xi)lines.push('X,'+v.x.values[i]+','+p.x[i]);for(const j of p.yi)lines.push('Y,'+v.y.values[j]+','+p.y[j]);const u=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='SpinPlot_2D_projection.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){alert(e.message);}};body.append(exportButton);box.ontoggle=()=>{s.open=box.open;};card.querySelector('.subplot-body').prepend(box);
 // 2D uses its own axis/projection controls; curve ordering and 1D processing are inapplicable.
 for(const e of card.querySelectorAll('.curve-manager'))e.style.display='none';}
function extent(a,ids){let lo=Infinity,hi=-Infinity;for(const i of ids){const v=a[i];if(Number.isFinite(v)){lo=Math.min(lo,v);hi=Math.max(hi,v);}}if(!Number.isFinite(lo))return[0,1];return[lo,hi===lo?lo+1:hi];}
function edge(a,i){return[i?(a[i-1]+a[i])/2:a[i]-(a[1]-a[0])/2,i<a.length-1?(a[i]+a[i+1])/2:a[i]+(a[i]-a[i-1])/2];}
function cellIndex(a,v){const asc=a.at(-1)>a[0],n=a.length;let lo=0,hi=n-1;while(lo<hi){const mid=(lo+hi)>>1,b=(a[mid]+a[mid+1])/2;if(asc?v>b:v<b)lo=mid+1;else hi=mid;}return lo;}
export function raster(m,width,height){const {v,xr,yr,max}=m,canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const c=canvas.getContext('2d'),image=c.createImageData(width,height),xs=Array.from({length:width},(_,i)=>cellIndex(v.x.values,xr[0]+(i+.5)/width*(xr[1]-xr[0]))),ys=Array.from({length:height},(_,j)=>cellIndex(v.y.values,yr[1]-(j+.5)/height*(yr[1]-yr[0])));for(let j=0;j<height;j++)for(let i=0;i<width;i++){const z=v.z[ys[j]][xs[i]],k=(j*width+i)*4;if(!Number.isFinite(z))continue;const t=Math.min(1,Math.abs(z)/max),b=Math.round(255*(1-t));image.data[k]=z>=0?255:b;image.data[k+1]=b;image.data[k+2]=z>=0?b:255;image.data[k+3]=255;}c.putImageData(image,0,0);return canvas;}
export function render(ctx,d,s,box,font,theme,title){const m=model(d,s),{v,p,xr,yr,max}=m,{cellX:cx,cellY:cy,cellW:w,cellH:h}=box;const proj=s.showProjections, x=cx+Math.min(64,w*.16),y=cy+(proj?h*.25:35),pw=w*(proj?.65:.80),ph=h*(proj?.60:.72),X=a=>x+(a-xr[0])/(xr[1]-xr[0])*pw,Y=a=>y+ph-(a-yr[0])/(yr[1]-yr[0])*ph;ctx.save();ctx.fillStyle=theme.text;ctx.font='11px '+font;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(title||d.name,cx+w/2,cy+12);ctx.save();ctx.beginPath();ctx.rect(x,y,pw,ph);ctx.clip();
 if(s.mode==='heatmap'){if(typeof ctx.drawImage==='function'){const scale=Math.min(2,window.devicePixelRatio||1),image=raster(m,Math.max(1,Math.ceil(pw*scale)),Math.max(1,Math.ceil(ph*scale)));ctx.drawImage(image,x,y,pw,ph);}else{// Vector export: retain cells without any data-size cutoff.
 for(const j of p.yi){const ye=edge(v.y.values,j).map(Y);for(const i of p.xi){const z=v.z[j][i];if(!Number.isFinite(z))continue;const xe=edge(v.x.values,i).map(X),b=Math.round(255*(1-Math.min(1,Math.abs(z)/max)));ctx.fillStyle=z>=0?`rgb(255,${b},${b})`:`rgb(${b},${b},255)`;ctx.fillRect(Math.min(...xe),Math.min(...ye),Math.abs(xe[1]-xe[0]),Math.abs(ye[1]-ye[0]));}}}
 }else{const rows=p.yi.filter((_,k)=>k%Number(s.step)===0);for(let k=0;k<rows.length;k++){const j=rows[k],base=y+ph*.95-k*ph*.85/Math.max(1,rows.length-1);ctx.strokeStyle=theme.text;ctx.beginPath();let open=false;for(const i of p.xi){const z=v.z[j][i];if(!Number.isFinite(z)){open=false;continue;}const px=X(v.x.values[i]),py=base-z/max*Number(s.offset)*ph*.4/Math.max(1,rows.length);if(open)ctx.lineTo(px,py);else ctx.moveTo(px,py);open=true;}ctx.stroke();ctx.fillStyle=theme.text;ctx.textAlign='right';ctx.fillText(v.y.values[j].toPrecision(3)+' '+v.y.unit,x+pw-3,base);}}
 ctx.restore();ctx.strokeStyle=theme.axis;ctx.lineWidth=1;ctx.strokeRect(x,y,pw,ph);ctx.fillStyle=theme.text;ctx.textAlign='center';for(let k=0;k<=4;k++){const a=xr[0]+(xr[1]-xr[0])*k/4,b=yr[0]+(yr[1]-yr[0])*k/4;ctx.fillText(a.toPrecision(4),X(a),y+ph+13);ctx.textAlign='right';ctx.fillText(b.toPrecision(4),x-5,Y(b));ctx.textAlign='center';}ctx.fillText(v.x.name+' ('+v.x.unit+')',x+pw/2,y+ph+32);ctx.save();ctx.translate(cx+12,y+ph/2);ctx.rotate(-Math.PI/2);ctx.fillText(v.y.name+' ('+v.y.unit+')',0,0);ctx.restore();
 if(proj){const [a,b]=extent(p.x,p.xi),[c,e]=extent(p.y,p.yi);function line(ids,get){ctx.beginPath();let open=false;for(const i of ids){const [px,py]=get(i);if(!Number.isFinite(px)||!Number.isFinite(py)){open=false;continue;}if(open)ctx.lineTo(px,py);else ctx.moveTo(px,py);open=true;}ctx.strokeStyle=theme.axis;ctx.stroke();}line(p.xi,i=>[X(v.x.values[i]),cy+h*.20-(p.x[i]-a)/(b-a)*h*.12]);line(p.yi,j=>[x+pw+w*.04+(p.y[j]-c)/(e-c)*w*.15,Y(v.y.values[j])]);ctx.fillText('X: '+s.xMode,x+pw/2,cy+h*.05+12);ctx.fillText('Y: '+s.yMode,x+pw+w*.12,y-12);}
 if(s.mode==='heatmap'){ctx.font='9px '+font;ctx.fillText('Blue −'+max.toPrecision(3)+' · white 0 · red +'+max.toPrecision(3),x+pw/2,y+ph+48);}ctx.restore();return{x0:x,y0:y,pw,ph,xmin:xr[0],xmax:xr[1],ymin:yr[0],ymax:yr[1],...box,twoD:true};}
