// Move existing controls instead of copying them, preserving IDs, events and saved settings.
export function organizeSubplot(card,sp,{axisInfo,frequency,onChange,onProcessing}){
 const root=card.querySelector('.subplot-body'),open=sp.uiOpen??={},field=k=>card.querySelector('[data-field="'+k+'"]'),two=k=>card.querySelector('[data-twod="'+k+'"]');
 function section(name,key,defaultOpen=false){const box=document.createElement('details');box.className='advanced-layout subplot-section';box.dataset.section=key;box.open=open[key]??defaultOpen;const summary=document.createElement('summary');summary.textContent=name;const body=document.createElement('div');body.className='local-block';box.append(summary,body);box.addEventListener('toggle',()=>{open[key]=box.open;});root.append(box);return {box,body};}
 function top(el,parent=root){while(el&&el.parentElement!==parent)el=el.parentElement;return el;}
 function move(el,target,parent=root){const node=top(el,parent);if(node)target.append(node);}
 const oldAxes=field('xUseGlobal').closest('details'),oldG=field('gUseGlobal').closest('details'),oldColor=field('colorSchemeOverride').closest('details'),oldLayout=field('gridRow').closest('details'),oldFreq=field('freqMode').closest('details'),oldAnnotations=card.querySelector('[data-annotation-details]'),oldProjection=two('xMode')?.closest('.subplot-body > details'),old2D=card.querySelector('.twod-options');
 const data=section('Data','data',true),plot=section('Plot mode','plot',true),legend=section('Legend & labels','legend'),processing=section('Processing parameters','processing');
 move(card.querySelector('.curve-manager'),data.body);move(field('mode'),plot.body);move(field('offsetScale'),plot.body);move(field('manualOffsets'),plot.body);
 if(old2D){const contents=old2D.querySelector('.local-block');plot.body.append(contents);contents.classList.remove('local-block');old2D.remove();}
 const stack=sp.mode==='stack';for(const key of ['offsetMode','offsetScale','offsetDirection','manualOffsets']){const el=field(key),wrap=el.closest('.field');wrap.hidden=!stack||(!!sp.twoD&&['offsetMode','offsetDirection','manualOffsets'].includes(key))||(!sp.twoD&&(key==='manualOffsets'?sp.offsetMode!=='manual':key==='offsetScale'&&sp.offsetMode==='manual'));}
 if(two('step'))two('step').parentElement.hidden=!stack;
 move(field('labelMode'),legend.body);move(field('directLabelX'),legend.body);const direct=sp.labelMode==='direct'||sp.labelMode==='both';field('directLabelX').closest('.grid2').hidden=!direct;field('legendPosition').closest('details').hidden=sp.labelMode==='none'||sp.labelMode==='direct';
 if(sp.twoD){field('labelMode').closest('.field').querySelector('label').textContent='Stack trace labels';for(const option of field('labelMode').options){option.textContent=option.value==='none'?'None':option.value==='legend'?'Trace values':option.textContent;option.hidden=!['legend','none'].includes(option.value);}field('legendPosition').closest('details').hidden=true;field('directLabelX').closest('.grid2').hidden=true;legend.box.hidden=!stack;}
 const links=field('showYTicks').closest('.link-row');for(const el of [...links.children])oldAxes.querySelector('.local-block').append(el);links.remove();
 const apply=card.querySelector('[data-action=applyAll]').parentElement;legend.body.append(apply);
 const noise=field('noiseRegions');move(noise,processing.body);move(card.querySelector('.noise-controls'),processing.body);move(field('showNoiseRegions'),processing.body);move(card.querySelector('.noise-draft'),processing.body);
 const noiseLabel=noise.closest('.field').querySelector('label');noiseLabel.textContent='Noise regions · '+axisInfo.x.name+(axisInfo.x.unit?' ('+axisInfo.x.unit+')':'');noise.placeholder='Coordinate ranges';const note=document.createElement('div');note.className='small processing-summary';note.textContent=sp.twoD?'2D signal is displayed directly; 1D baseline and noise scaling do not apply.':'Noise regions: '+(sp.noiseRegions||'automatic diff-MAD');processing.body.prepend(note);
 for(const el of [...processing.body.children])if(el!==note)el.hidden=true;
 const full=document.createElement('button');full.type='button';full.textContent='Open Processing';full.onclick=onProcessing;processing.body.append(full);oldFreq.querySelector('summary').firstChild.textContent='Frequency alignment / g frequency ';processing.body.append(oldFreq);
 const gNote=document.createElement('div');gNote.className='small';gNote.textContent='Frequency: '+(Number.isFinite(frequency)?frequency.toFixed(6)+' GHz':'unavailable')+' · '+(sp.freqMode==='inherit'?'global setting':sp.freqMode==='local'?'subplot setting':'alignment disabled');oldG.querySelector('.local-block').prepend(gNote);
 oldAxes.querySelector('summary').firstChild.textContent=sp.twoD?'Axes · X / Y / Z ':'Axes · X / Y ';oldG.querySelector('summary').firstChild.textContent='g axis ';oldColor.querySelector('summary').firstChild.textContent='Colors ';oldLayout.querySelector('summary').textContent='Advanced layout';
 // Split the axes into matching nested sections; range inheritance has an explicit scope.
 const axesBody=oldAxes.querySelector('.local-block');for(const axis of ['x','y']){const A=axis.toUpperCase(),part=section(A+' axis','axis'+A);for(const k of [axis+'UseGlobal',axis+'Min',axis+'TickDigits',axis==='x'?'linkX':'linkY',...(axis==='y'?['showYTicks']:[])])move(field(k),part.body,axesBody);field(axis+'UseGlobal').nextElementSibling.textContent='Use global '+A+' range / step';const title=two(axis+'Label');if(title)move(title,part.body,axesBody);if(!title){const wrap=document.createElement('div');wrap.className='field';const label=document.createElement('label');label.textContent=A+' axis title';const input=document.createElement('input');input.value=sp[axis+'AxisLabel']||'';input.placeholder='Inherit global / coordinate name';input.dataset.field=axis+'AxisLabel';input.onchange=()=>{sp[axis+'AxisLabel']=input.value;onChange();};wrap.append(label,input);part.body.append(wrap);}axesBody.append(part.box);}
 if(sp.twoD){const z=section('Z axis / colorbar','axisZ');for(const k of ['zUseGlobal','zMin','colorbarLabel','hideColorbarTitle','showColorbar'])move(two(k),z.body,axesBody);const auto=[...axesBody.children].find(e=>e.tagName==='BUTTON'&&e.textContent==='Auto Z');if(auto)z.body.append(auto);axesBody.append(z.box);}
 if(oldProjection){oldProjection.querySelector('summary').textContent='Projections';oldProjection.open=open.projections??true;oldProjection.addEventListener('toggle',()=>{open.projections=oldProjection.open;});const body=oldProjection.querySelector('.local-block');for(const [axis,name,keys]of [['x','Top projection',['xMode','projectionYMin','projectionYMax','xProjectionMin','xProjectionMax','showXProjection','showXProjectionRange','showXProjectionTitle','xProjectionTitle']],['y','Right projection',['yMode','projectionXMin','projectionXMax','yProjectionMin','yProjectionMax','showYProjection','showYProjectionRange','showYProjectionTitle','yProjectionTitle']]]){const part=section(name,'projection'+axis,true);part.body.classList.add('grid2');for(const k of keys){const el=two(k);move(el,part.body,body);if(k.startsWith('projection')){const source=axis==='x'?axisInfo.y:axisInfo.x;el.parentElement.firstChild.textContent='Compute over '+source.name+(source.unit?' ('+source.unit+')':'')+': '+(k.endsWith('Min')?'min':'max');}}body.append(part.box);}body.classList.remove('grid2');const positions=[...body.children].find(e=>e.tagName==='DETAILS'&&e.querySelector('summary').textContent==='Range label positions');if(positions)body.append(positions);}
 for(const e of [...root.children])if(e.classList.contains('sep'))e.remove();
 root.append(data.box,plot.box,oldAxes,oldG,oldColor,legend.box);if(oldProjection)root.append(oldProjection);root.append(oldAnnotations,processing.box,oldLayout);
 const status=()=>{if(!sp.twoD)note.textContent='Noise regions: '+(sp.noiseRegions||'automatic diff-MAD');const local=(!sp.xUseGlobal||!sp.yUseGlobal)||['xTickDigits','yTickDigits','xAxisLabel','yAxisLabel'].some(k=>sp[k]!==''&&sp[k]!==undefined)||['xTickNotation','yTickNotation'].some(k=>sp[k]&&sp[k]!=='inherit')||!!sp.twoD&&(sp.twoD.settings.zUseGlobal===false||sp.twoD.settings.xLabel||sp.twoD.settings.yLabel||sp.twoD.settings.colorbarTitleUseGlobal===false);const tag=oldAxes.querySelector('.override-tag');tag.textContent=local?'LOCAL':'GLOBAL';tag.classList.toggle('local',!!local);const gt=oldG.querySelector('.override-tag');gt.textContent=sp.gUseGlobal?'GLOBAL':'LOCAL';gt.classList.toggle('local',!sp.gUseGlobal);const colors=sp.colorSchemeOverride!=='inherit'||!!sp.twoD&&(sp.twoD.settings.scheme!=='inherit'||sp.twoD.settings.projectionScheme!=='inherit'),ct=oldColor.querySelector('.override-tag');ct.textContent=colors?'LOCAL':'GLOBAL';ct.classList.toggle('local',!!colors);};status();card.addEventListener('change',status);
}
